import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "@/provider/react-query";
import ProgressProvider from "@/provider/proggres-bar";
import { Toaster } from "sonner";
import { Providers } from "@/provider/next-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ReactQueryClientProvider>
            <ProgressProvider>{children}</ProgressProvider>
            <Toaster closeButton position="top-right" richColors />
          </ReactQueryClientProvider>
        </Providers>
      </body>
    </html>
  );
}
