import {
  BookOpen,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  Clock,
  Edit,
  ExternalLink,
  Eye,
  Filter,
  Github,
  Heart,
  Home,
  Instagram,
  Link,
  Loader,
  Mail,
  Menu,
  MoreHorizontal,
  Plus,
  Search,
  Star,
  StarOff,
  Trash2,
  X,
} from "lucide-react";

type IconProps = React.HTMLAttributes<SVGElement>;
export const Icons = {
  Menu: (props: IconProps) => <Menu {...props} />,
  Home: (props: IconProps) => <Home {...props} />,
  Github: (props: IconProps) => <Github {...props} />,
  Mail: (props: IconProps) => <Mail {...props} />,
  Instagram: (props: IconProps) => <Instagram {...props} />,
  Trash2: (props: IconProps) => <Trash2 {...props} />,
  ExternalLink: (props: IconProps) => <ExternalLink {...props} />,
  Edit: (props: IconProps) => <Edit {...props} />,
  Search: (props: IconProps) => <Search {...props} />,
  Plus: (props: IconProps) => <Plus {...props} />,
  Filter: (props: IconProps) => <Filter {...props} />,
  X: (props: IconProps) => <X {...props} />,
  Eye: (props: IconProps) => <Eye {...props} />,
  Link: (props: IconProps) => <Link {...props} />,
  MoreHorizontal: (props: IconProps) => <MoreHorizontal {...props} />,
  Star: (props: IconProps) => <Star {...props} />,
  StarOff: (props: IconProps) => <StarOff {...props} />,
  Calendar: (props: IconProps) => <Calendar {...props} />,
  Clock: (props: IconProps) => <Clock {...props} />,
  BookOpen: (props: IconProps) => <BookOpen {...props} />,
  Heart: (props: IconProps) => <Heart {...props} />,
  Loader: (props: IconProps) => <Loader {...props} />,
  ChevronDown: (props: IconProps) => <ChevronDown {...props} />,
  ChevronLeft: (props: IconProps) => <ChevronLeft {...props} />,
  Check: (props: IconProps) => <Check {...props} />,
};
